language: go
go:
- 1.8

install:
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega

script: go test -v `go list ./... | grep -v vendor` -args -ginkgo.randomizeAllSpecs -ginkgo.trace