language: go
go:
- "1.11"

install:
- go get github.com/onsi/ginkgo/ginkgo
- go get github.com/onsi/gomega
- go get github.com/sirupsen/logrus

script: go test -v ./... -args -ginkgo.randomizeAllSpecs -ginkgo.trace